/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penentuanblmfpso;

import Kontroller.FCM;
import Kontroller.FPSO_FCM;
import Model.DataKelayakan;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    
    private final PembentukanClusterBLM pembentukanClusterBLM;
    private final PenentuanPenerimaanBLM penentuanPenerimaanBLM;
    private int nData;
    private double[][] dataWarga;
    private DataKelayakan[] dataKelayakan;
    private FPSO_FCM fpso_fcm;
    private FCM fcm;
    
    public MenuUtama() {
        initComponents();
        penentuanPenerimaanBLM = new PenentuanPenerimaanBLM();
        pembentukanClusterBLM = new PembentukanClusterBLM();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PembentukanCluster = new javax.swing.JButton();
        PenentuanPenerimaan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Penentuan Penerima BLM menggunakan metode hybrid FPSO dan FCM");

        PembentukanCluster.setText("Pembentukan CLuster");
        PembentukanCluster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PembentukanClusterActionPerformed(evt);
            }
        });

        PenentuanPenerimaan.setText("Penentuan Penerimaan BLM");
        PenentuanPenerimaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenentuanPenerimaanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(PembentukanCluster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PenentuanPenerimaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PembentukanCluster, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PenentuanPenerimaan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PembentukanClusterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PembentukanClusterActionPerformed
        // TODO add your handling code here:
        pembentukanClusterBLM.setVisible(true);
    }//GEN-LAST:event_PembentukanClusterActionPerformed

    private void PenentuanPenerimaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenentuanPenerimaanActionPerformed
        // TODO add your handling code here:
        if(setInisialisasiData()){
            penentuanPenerimaanBLM.setNData(nData);
            penentuanPenerimaanBLM.setDataWarga(dataWarga);
            penentuanPenerimaanBLM.setDataKelayakan(dataKelayakan);
            penentuanPenerimaanBLM.setFPSO_FCM(fpso_fcm);
            penentuanPenerimaanBLM.setFCM(fcm);
            penentuanPenerimaanBLM.setVisible(true);
        }
    }//GEN-LAST:event_PenentuanPenerimaanActionPerformed

    public boolean setInisialisasiData(){
        boolean isDone = false;
        if(pembentukanClusterBLM.getNData() == 0){
            JOptionPane.showMessageDialog(null, "Anda belum melakukan proses pembentukan cluster");
        }
        else{
            isDone = true;
            nData = pembentukanClusterBLM.getNData();
            dataWarga = pembentukanClusterBLM.getDataWarga();
            dataKelayakan = pembentukanClusterBLM.getDataKelayakan();
            fpso_fcm = pembentukanClusterBLM.getFPSO_FCM();
            fcm = pembentukanClusterBLM.getFCM();
        }
        
        return isDone;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PembentukanCluster;
    private javax.swing.JButton PenentuanPenerimaan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
