/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penentuanblmfpso;

import Kontroller.DokumenManager;
import Kontroller.FCM;
import Kontroller.FPSO_FCM;
import Model.DataKelayakan;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class PenentuanPenerimaanBLM extends javax.swing.JFrame {

    /**
     * Creates new form Pengujian
     */
    private int nData, nAttribut;
    private double[][] dataWargaAtt;
    private DataKelayakan[] dataKelayakan;
    private FPSO_FCM fpso_fcm;
    private FCM fcm;
    
    public PenentuanPenerimaanBLM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PenentuanPenerimaanBLM = new javax.swing.JLabel();
        B_FPSO_FCM = new javax.swing.JButton();
        B_FCM = new javax.swing.JButton();
        HasilFPSO_FCM = new javax.swing.JLabel();
        TB_Kelayakan1 = new javax.swing.JTabbedPane();
        P_Layak1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelLayakFPSO_FCM = new javax.swing.JTable();
        P_KurangLayak1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TabelKurangLayakFPSO_FCM = new javax.swing.JTable();
        P_TidakLayak1 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TabelTidakLayakFPSO_FCM = new javax.swing.JTable();
        HasilFCM = new javax.swing.JLabel();
        TB_Kelayakan = new javax.swing.JTabbedPane();
        P_Layak = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelLayakFCM = new javax.swing.JTable();
        P_KurangLayak = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TabelKurangLayakFCM = new javax.swing.JTable();
        P_TidakLayak = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TabelTidakLayakFCM = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Pelatihan"); // NOI18N

        PenentuanPenerimaanBLM.setFont(new java.awt.Font("Andalus", 0, 30)); // NOI18N
        PenentuanPenerimaanBLM.setText("Penentuan Penerimaan BLM ");

        B_FPSO_FCM.setText("FPSO_FCM Proses");
        B_FPSO_FCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_FPSO_FCMActionPerformed(evt);
            }
        });

        B_FCM.setText("FCM Proses");
        B_FCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_FCMActionPerformed(evt);
            }
        });

        HasilFPSO_FCM.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        HasilFPSO_FCM.setText("Hasil Pemrosesan FPSO-FCM");

        TabelLayakFPSO_FCM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Jenis Kelamin", "Usia KK", "Alamat", "Pekerjaan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelLayakFPSO_FCM);

        javax.swing.GroupLayout P_Layak1Layout = new javax.swing.GroupLayout(P_Layak1);
        P_Layak1.setLayout(P_Layak1Layout);
        P_Layak1Layout.setHorizontalGroup(
            P_Layak1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_Layak1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
                .addContainerGap())
        );
        P_Layak1Layout.setVerticalGroup(
            P_Layak1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_Layak1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TB_Kelayakan1.addTab("Layak", P_Layak1);

        TabelKurangLayakFPSO_FCM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Jenis Kelamin", "Usia KK", "Alamat", "Pekerjaan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(TabelKurangLayakFPSO_FCM);

        javax.swing.GroupLayout P_KurangLayak1Layout = new javax.swing.GroupLayout(P_KurangLayak1);
        P_KurangLayak1.setLayout(P_KurangLayak1Layout);
        P_KurangLayak1Layout.setHorizontalGroup(
            P_KurangLayak1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_KurangLayak1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
                .addContainerGap())
        );
        P_KurangLayak1Layout.setVerticalGroup(
            P_KurangLayak1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_KurangLayak1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TB_Kelayakan1.addTab("Kurang Layak", P_KurangLayak1);

        TabelTidakLayakFPSO_FCM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Jenis Kelamin", "Usia KK", "Alamat", "Pekerjaan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(TabelTidakLayakFPSO_FCM);

        javax.swing.GroupLayout P_TidakLayak1Layout = new javax.swing.GroupLayout(P_TidakLayak1);
        P_TidakLayak1.setLayout(P_TidakLayak1Layout);
        P_TidakLayak1Layout.setHorizontalGroup(
            P_TidakLayak1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_TidakLayak1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
                .addContainerGap())
        );
        P_TidakLayak1Layout.setVerticalGroup(
            P_TidakLayak1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_TidakLayak1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TB_Kelayakan1.addTab("Tidak Layak", P_TidakLayak1);

        HasilFCM.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        HasilFCM.setText("Hasil Pemrosesan FCM");

        TabelLayakFCM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Jenis Kelamin", "Usia KK", "Alamat", "Pekerjaan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelLayakFCM.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(TabelLayakFCM);
        TabelLayakFCM.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout P_LayakLayout = new javax.swing.GroupLayout(P_Layak);
        P_Layak.setLayout(P_LayakLayout);
        P_LayakLayout.setHorizontalGroup(
            P_LayakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_LayakLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
                .addContainerGap())
        );
        P_LayakLayout.setVerticalGroup(
            P_LayakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_LayakLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TB_Kelayakan.addTab("Layak", P_Layak);

        TabelKurangLayakFCM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Jenis Kelamin", "Usia KK", "Alamat", "Pekerjaan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TabelKurangLayakFCM);

        javax.swing.GroupLayout P_KurangLayakLayout = new javax.swing.GroupLayout(P_KurangLayak);
        P_KurangLayak.setLayout(P_KurangLayakLayout);
        P_KurangLayakLayout.setHorizontalGroup(
            P_KurangLayakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_KurangLayakLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
                .addContainerGap())
        );
        P_KurangLayakLayout.setVerticalGroup(
            P_KurangLayakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_KurangLayakLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TB_Kelayakan.addTab("Kurang Layak", P_KurangLayak);

        TabelTidakLayakFCM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Jenis Kelamin", "Usia KK", "Alamat", "Pekerjaan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(TabelTidakLayakFCM);

        javax.swing.GroupLayout P_TidakLayakLayout = new javax.swing.GroupLayout(P_TidakLayak);
        P_TidakLayak.setLayout(P_TidakLayakLayout);
        P_TidakLayakLayout.setHorizontalGroup(
            P_TidakLayakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_TidakLayakLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
                .addContainerGap())
        );
        P_TidakLayakLayout.setVerticalGroup(
            P_TidakLayakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_TidakLayakLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TB_Kelayakan.addTab("Tidak Layak", P_TidakLayak);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(B_FPSO_FCM, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B_FCM, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TB_Kelayakan1)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TB_Kelayakan)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(HasilFPSO_FCM)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(HasilFCM))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(PenentuanPenerimaanBLM)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PenentuanPenerimaanBLM)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_FPSO_FCM, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_FCM, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HasilFPSO_FCM)
                .addGap(1, 1, 1)
                .addComponent(TB_Kelayakan1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HasilFCM)
                .addGap(1, 1, 1)
                .addComponent(TB_Kelayakan, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_FPSO_FCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_FPSO_FCMActionPerformed
        // TODO add your handling code here:
        int i;
        String[] dataLayak;
        
        dataLayak = fpso_fcm.getFPSO_FCM();

        for(i=0; i<nData; i++){
            dataKelayakan[i].setTunjangan(dataLayak[i]);
        }

        String[] row = new String[6];
        DefaultTableModel Tabel_Layak_Model = (DefaultTableModel) TabelLayakFPSO_FCM.getModel();
        DefaultTableModel Tabel_KurangLayak_Model = (DefaultTableModel) TabelKurangLayakFPSO_FCM.getModel();
        DefaultTableModel Tabel_TidakLayak_Model = (DefaultTableModel) TabelTidakLayakFPSO_FCM.getModel();

        int nLayak, nKrngLayak, nTdkLayak;
        nLayak = nKrngLayak = nTdkLayak = 1;

        for(i=0; i<nData; i++){
            if("Layak".equals(dataKelayakan[i].getTunjangan())){
                row[0] = String.valueOf(nLayak);
                row[1] = dataKelayakan[i].getNama();
                row[2] = dataKelayakan[i].getJenisKelamin();
                row[3] = String.valueOf(dataKelayakan[i].getUsia());
                row[4] = dataKelayakan[i].getAlamat();
                row[5] = dataKelayakan[i].getPekerjaan();

                Tabel_Layak_Model.addRow(row);
                nLayak = nLayak+1;
            }

            if("Kurang Layak".equals(dataKelayakan[i].getTunjangan())){
                row[0] = String.valueOf(nKrngLayak);
                row[1] = dataKelayakan[i].getNama();
                row[2] = dataKelayakan[i].getJenisKelamin();
                row[3] = String.valueOf(dataKelayakan[i].getUsia());
                row[4] = dataKelayakan[i].getAlamat();
                row[5] = dataKelayakan[i].getPekerjaan();

                Tabel_KurangLayak_Model.addRow(row);
                nKrngLayak = nKrngLayak+1;
            }

            if("Tidak Layak".equals(dataKelayakan[i].getTunjangan())){
                row[0] = String.valueOf(nTdkLayak);
                row[1] = dataKelayakan[i].getNama();
                row[2] = dataKelayakan[i].getJenisKelamin();
                row[3] = String.valueOf(dataKelayakan[i].getUsia());
                row[4] = dataKelayakan[i].getAlamat();
                row[5] = dataKelayakan[i].getPekerjaan();

                Tabel_TidakLayak_Model.addRow(row);
                nTdkLayak = nTdkLayak+1;
            }
        }
    }//GEN-LAST:event_B_FPSO_FCMActionPerformed

    private void B_FCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_FCMActionPerformed
        // TODO add your handling code here:
        int i;
        String[] dataLayak;
        dataLayak = fcm.getFCM();

        for(i=0; i<nData; i++){
            dataKelayakan[i].setTunjangan(dataLayak[i]);
        }

        String[] row = new String[6];
        DefaultTableModel Tabel_Layak_Model = (DefaultTableModel) TabelLayakFCM.getModel();
        DefaultTableModel Tabel_KurangLayak_Model = (DefaultTableModel) TabelKurangLayakFCM.getModel();
        DefaultTableModel Tabel_TidakLayak_Model = (DefaultTableModel) TabelTidakLayakFCM.getModel();

        int nLayak, nKrngLayak, nTdkLayak;
        nLayak = nKrngLayak = nTdkLayak = 1;

        for(i=0; i<nData; i++){
            if("Layak".equals(dataKelayakan[i].getTunjangan())){
                row[0] = String.valueOf(nLayak);
                row[1] = dataKelayakan[i].getNama();
                row[2] = dataKelayakan[i].getJenisKelamin();
                row[3] = String.valueOf(dataKelayakan[i].getUsia());
                row[4] = dataKelayakan[i].getAlamat();
                row[5] = dataKelayakan[i].getPekerjaan();

                Tabel_Layak_Model.addRow(row);
                nLayak = nLayak+1;
            }

            if("Kurang Layak".equals(dataKelayakan[i].getTunjangan())){
                row[0] = String.valueOf(nKrngLayak);
                row[1] = dataKelayakan[i].getNama();
                row[2] = dataKelayakan[i].getJenisKelamin();
                row[3] = String.valueOf(dataKelayakan[i].getUsia());
                row[4] = dataKelayakan[i].getAlamat();
                row[5] = dataKelayakan[i].getPekerjaan();

                Tabel_KurangLayak_Model.addRow(row);
                nKrngLayak = nKrngLayak+1;
            }

            if("Tidak Layak".equals(dataKelayakan[i].getTunjangan())){
                row[0] = String.valueOf(nTdkLayak);
                row[1] = dataKelayakan[i].getNama();
                row[2] = dataKelayakan[i].getJenisKelamin();
                row[3] = String.valueOf(dataKelayakan[i].getUsia());
                row[4] = dataKelayakan[i].getAlamat();
                row[5] = dataKelayakan[i].getPekerjaan();

                Tabel_TidakLayak_Model.addRow(row);
                nTdkLayak = nTdkLayak+1;
            }
        }
    }//GEN-LAST:event_B_FCMActionPerformed

    public void setNData(int nData){
        this.nData = nData;
    }
    
    public void setDataKelayakan(DataKelayakan[] dataKelayakan){
        this.dataKelayakan = dataKelayakan;
    }
    
    public void setDataWarga(double[][] dataWargaAtt){
        this.dataWargaAtt = dataWargaAtt;
    }
    
    public void setFPSO_FCM(FPSO_FCM fpso_fcm){
        this.fpso_fcm = fpso_fcm;
    }
    
    public void setFCM(FCM fcm){
        this.fcm = fcm;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenentuanPenerimaanBLM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenentuanPenerimaanBLM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenentuanPenerimaanBLM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenentuanPenerimaanBLM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenentuanPenerimaanBLM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_FCM;
    private javax.swing.JButton B_FPSO_FCM;
    private javax.swing.JLabel HasilFCM;
    private javax.swing.JLabel HasilFPSO_FCM;
    private javax.swing.JPanel P_KurangLayak;
    private javax.swing.JPanel P_KurangLayak1;
    private javax.swing.JPanel P_Layak;
    private javax.swing.JPanel P_Layak1;
    private javax.swing.JPanel P_TidakLayak;
    private javax.swing.JPanel P_TidakLayak1;
    private javax.swing.JLabel PenentuanPenerimaanBLM;
    private javax.swing.JTabbedPane TB_Kelayakan;
    private javax.swing.JTabbedPane TB_Kelayakan1;
    private javax.swing.JTable TabelKurangLayakFCM;
    private javax.swing.JTable TabelKurangLayakFPSO_FCM;
    private javax.swing.JTable TabelLayakFCM;
    private javax.swing.JTable TabelLayakFPSO_FCM;
    private javax.swing.JTable TabelTidakLayakFCM;
    private javax.swing.JTable TabelTidakLayakFPSO_FCM;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
